---
services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    volumes:
      - ./data:/opt/sonarqube/data
      - ./logs:/opt/sonarqube/logs
      - ./extensions:/opt/sonarqube/extensions            
    ports:
      - 9000:9000
#     networks:
#       - sonarnet
#     healthcheck:
#       test: ["CMD-SHELL", "curl", "http://localhost:9000/sessions/new?return_to=%2Fprojects", "||", "exit", "1"]
#       interval: 20s
#       timeout: 30s
#       retries: 5
#       start_period: 30s
  
#   sonar-scan:
#     image: sonarsource/sonar-scanner-cli:latest
#     container_name: sonar-scanner-cli
#     volumes:
#       - ./sonar-data:/usr/src
#     networks:
#       - sonarnet
#     depends_on:
#       sonarqube:
#         condition: service_healthy

# networks:
#   sonarnet:
#     driver: bridge