FROM node:latest AS base

WORKDIR /app

COPY ./package.json ./

RUN npm install

COPY ./ ./



FROM base AS development

CMD ["npm", "run", "start"]



FROM base AS build 

RUN npm run build



FROM node:latest AS production

WORKDIR /app

COPY --from=build /app/dist ./dist

COPY ./package*.json ./

RUN npm ci --omit=dev

CMD ["node", "dist/main.js"]